# -*- coding: utf-8 -*-
"""идз_итог

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9Jncz-m84AkPrvmONPhyLr0SgS_B5bj
"""

# Установка необходимых библиотек
!pip install arch
!pip install prophet
!pip install seaborn
!pip install statsmodels

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tsa.stattools import adfuller, grangercausalitytests
from arch import arch_model
from prophet import Prophet
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
import warnings
warnings.filterwarnings('ignore')

plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['figure.figsize'] = (12, 6)

# Загрузка данных Транснефти
trnfp_data = pd.read_csv('TRNFP_231215_251215.csv', sep=';', parse_dates=['<DATE>'], dayfirst=True)
trnfp_data.rename(columns={'<TICKER>': 'Ticker', '<PER>': 'Period', '<DATE>': 'Date',
                           '<TIME>': 'Time', '<CLOSE>': 'Close', '<VOL>': 'Volume'}, inplace=True)
trnfp_data = trnfp_data[['Date', 'Close']]
trnfp_data.set_index('Date', inplace=True)

# Создаем полный диапазон дат
all_dates = pd.date_range(start=trnfp_data.index.min(), end=trnfp_data.index.max(), freq='D')
trnfp_full = trnfp_data.reindex(all_dates)

# Заполняем пропуски методом forward fill (значениями предыдущих дней)
trnfp_full['Close'] = trnfp_full['Close'].ffill()
trnfp_full.reset_index(inplace=True)
trnfp_full.rename(columns={'index': 'Date'}, inplace=True)

# Загрузка данных USD/RUB
usd_rub = pd.read_csv('USD_RUB Historical Data (1).csv', parse_dates=['Date'], dayfirst=True)
usd_rub['Price'] = usd_rub['Price'].astype(str).str.replace(',', '').astype(float)
usd_rub = usd_rub[['Date', 'Price']]
usd_rub.rename(columns={'Price': 'USD_RUB'}, inplace=True)

# Создаем полный диапазон дат для USD/RUB
all_dates_usd = pd.date_range(start=usd_rub['Date'].min(), end=usd_rub['Date'].max(), freq='D')
usd_rub_full = usd_rub.set_index('Date').reindex(all_dates_usd)
usd_rub_full['USD_RUB'] = usd_rub_full['USD_RUB'].ffill()
usd_rub_full.reset_index(inplace=True)
usd_rub_full.rename(columns={'index': 'Date'}, inplace=True)

# Загрузка данных Brent Oil
brent = pd.read_csv('Brent Oil Futures Historical Data (1).csv', parse_dates=['Date'], dayfirst=True)
brent['Price'] = brent['Price'].astype(float)
brent = brent[['Date', 'Price']]
brent.rename(columns={'Price': 'Brent'}, inplace=True)

# Создаем полный диапазон дат для Brent
all_dates_brent = pd.date_range(start=brent['Date'].min(), end=brent['Date'].max(), freq='D')
brent_full = brent.set_index('Date').reindex(all_dates_brent)
brent_full['Brent'] = brent_full['Brent'].ffill()
brent_full.reset_index(inplace=True)
brent_full.rename(columns={'index': 'Date'}, inplace=True)

# Объединяем все данные
data = trnfp_full.copy()
data = pd.merge(data, usd_rub_full, on='Date', how='left')
data = pd.merge(data, brent_full, on='Date', how='left')

# Заполняем пропуски в объединенных данных
data['USD_RUB'] = data['USD_RUB'].ffill()
data['Brent'] = data['Brent'].ffill()

print("="*60)
print("ПРЕДОБРАБОТКА ДАННЫХ ЗАВЕРШЕНА")
print("="*60)
print(f"Размерность датасета: {data.shape}")
print(f"Количество пропусков: {data.isnull().sum().sum()}")

# График цен Транснефти
fig, axes = plt.subplots(3, 1, figsize=(14, 12))

# 1. Цены Транснефти
axes[0].plot(data['Date'], data['Close'], label='Цена акции Транснефти', color='blue', linewidth=1)
axes[0].set_title('Динамика цен акций Транснефти', fontsize=14, fontweight='bold')
axes[0].set_ylabel('Цена (руб.)')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# 2. Курс USD/RUB
axes[1].plot(data['Date'], data['USD_RUB'], label='USD/RUB', color='green', linewidth=1)
axes[1].set_title('Динамика курса USD/RUB', fontsize=14, fontweight='bold')
axes[1].set_ylabel('Курс (руб.)')
axes[1].legend()
axes[1].grid(True, alpha=0.3)

# 3. Цены на нефть Brent
axes[2].plot(data['Date'], data['Brent'], label='Нефть Brent', color='red', linewidth=1)
axes[2].set_title('Динамика цен на нефть Brent', fontsize=14, fontweight='bold')
axes[2].set_ylabel('Цена ($)')
axes[2].set_xlabel('Дата')
axes[2].legend()
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('time_series_visualization_trnfp.png', dpi=300, bbox_inches='tight')
plt.show()

total_days = len(data)
test_days = 2  # Изменение: только 2 дня в тестовой выборке
split_idx = total_days - test_days

train_data = data.iloc[:split_idx].copy()
test_data = data.iloc[split_idx:].copy()

print(f"\nРАЗДЕЛЕНИЕ ДАННЫХ:")
print(f"Всего дней: {total_days}")
print(f"Тренировочная выборка: {len(train_data)} дней ({train_data['Date'].min()} - {train_data['Date'].max()})")
print(f"Тестовая выборка: {len(test_data)} дней ({test_data['Date'].min()} - {test_data['Date'].max()})")

"""Строим модели.

ARIMA
"""

# Проверка стационарности
def check_stationarity(series, name="Ряд"):
    result = adfuller(series.dropna())
    print(f"Тест Дики-Фуллера для {name}:")
    print(f"ADF Statistic: {result[0]:.4f}")
    print(f"p-value: {result[1]:.4f}")
    if result[1] <= 0.05:
        print(f"Вывод: {name} стационарен (p-value < 0.05)")
    else:
        print(f"Вывод: {name} нестационарен (p-value > 0.05)")
    print("-" * 50)
    return result[1]

p_value_original = check_stationarity(train_data['Close'], "оригинального ряда цен Транснефти")

# Если ряд нестационарен, берем первые разности
if p_value_original > 0.05:
    train_data['Close_diff'] = train_data['Close'].diff()
    p_value_diff = check_stationarity(train_data['Close_diff'].dropna(), "первых разностей цен Транснефти")
    use_diff = True
else:
    use_diff = False

# ACF и PACF графики для определения параметров ARIMA
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

# Вычисляем первые разности для анализа
ts_diff = train_data['Close'].diff().dropna()

# Графики ACF и PACF
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# ACF оригинального ряда
plot_acf(train_data['Close'].dropna(), lags=40, ax=axes[0, 0], alpha=0.05)
axes[0, 0].set_title('ACF оригинального ряда цен Транснефти', fontsize=12)
axes[0, 0].set_xlabel('Лаг')
axes[0, 0].set_ylabel('Автокорреляция')

# PACF оригинального ряда
plot_pacf(train_data['Close'].dropna(), lags=40, ax=axes[0, 1], alpha=0.05, method='ywm')
axes[0, 1].set_title('PACF оригинального ряда цен Транснефти', fontsize=12)
axes[0, 1].set_xlabel('Лаг')
axes[0, 1].set_ylabel('Частичная автокорреляция')

# ACF первых разностей
plot_acf(ts_diff, lags=40, ax=axes[1, 0], alpha=0.05)
axes[1, 0].set_title('ACF первых разностей цен Транснефти', fontsize=12)
axes[1, 0].set_xlabel('Лаг')
axes[1, 0].set_ylabel('Автокорреляция')

# PACF первых разностей
plot_pacf(ts_diff, lags=40, ax=axes[1, 1], alpha=0.05, method='ywm')
axes[1, 1].set_title('PACF первых разностей цен Транснефти', fontsize=12)
axes[1, 1].set_xlabel('Лаг')
axes[1, 1].set_ylabel('Частичная автокорреляция')

plt.suptitle('ACF и PACF графики для определения параметров ARIMA', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('acf_pacf_plots_trnfp.png', dpi=300, bbox_inches='tight')
plt.show()

# Определяем d (порядок дифференцирования)
d = 1  # на основе теста Дики-Фуллера и ACF графика

if d == 1:
    # Тестируем несколько вариантов на основе ACF/PACF анализа
    print("\nТестирование различных порядков ARIMA на основе ACF/PACF:")
    orders_to_test = [(1,1,1), (1,1,2), (2,1,1), (2,1,2), (0,1,0)]
    best_aic = np.inf
    best_order = None
    best_model = None

    for order in orders_to_test:
        try:
            model = ARIMA(train_data['Close'], order=order)
            model_fit = model.fit()
            print(f"ARIMA{order}: AIC = {model_fit.aic:.2f}, BIC = {model_fit.bic:.2f}")
            if model_fit.aic < best_aic:
                best_aic = model_fit.aic
                best_order = order
                best_model = model_fit
        except Exception as e:
            print(f"ARIMA{order}: не удалось оценить - {str(e)}")

    print(f"\nЛучшая модель: ARIMA{best_order} с AIC = {best_aic:.2f}")

    # Выводим более подробную информацию о выбранной модели
    print("\nОБОСНОВАНИЕ ВЫБОРА ПАРАМЕТРОВ:")
    print(f"p={best_order[0]}: количество лагов AR на основе PACF графика")
    print(f"d={best_order[1]}: порядок дифференцирования на основе теста стационарности")
    print(f"q={best_order[2]}: количество лагов MA на основе ACF графика")

    arima_fit = best_model
else:
    # Если d не равно 1, нужно определить порядок arima_order
    # Предположим, что arima_order определен где-то ранее
    if 'arima_order' not in locals() and 'arima_order' not in globals():
        arima_order = (1, 0, 1)  # Значение по умолчанию

    arima_model = ARIMA(train_data['Close'], order=arima_order)
    arima_fit = arima_model.fit()

print("\n" + "="*50)
print("РЕЗУЛЬТАТЫ ARIMA МОДЕЛИ:")
print("="*50)
print(arima_fit.summary())

# Прогноз на тестовую выборку (2 дня)
arima_forecast = arima_fit.forecast(steps=len(test_data))
test_data['ARIMA_Forecast'] = arima_forecast.values

# Вычисление ошибок прогноза на тестовой выборке
test_errors = test_data['Close'] - test_data['ARIMA_Forecast']
test_mae = np.mean(np.abs(test_errors))
test_rmse = np.sqrt(np.mean(test_errors**2))
test_mape = np.mean(np.abs(test_errors / test_data['Close'])) * 100

print(f"\nПРОГНОЗ НА ТЕСТОВОЙ ВЫБОРКЕ ({len(test_data)} дней):")
print(f"   MAE (средняя абсолютная ошибка):  {test_mae:.2f}")
print(f"   RMSE (среднеквадратичная ошибка): {test_rmse:.2f}")
print(f"   MAPE (средняя абсолютная процентная ошибка): {test_mape:.2f}%")

# Визуализация прогноза ARIMA с акцентом на последние 3 месяца
last_3_months = data['Date'].max() - timedelta(days=90)
recent_data = data[data['Date'] >= last_3_months]
recent_train = train_data[train_data['Date'] >= last_3_months]
recent_test = test_data

plt.figure(figsize=(14, 8))

# Построение линий графика
plt.plot(recent_train['Date'], recent_train['Close'], label='Факт (Обучающая выборка)', color='blue', linewidth=2)
plt.plot(recent_test['Date'], recent_test['Close'], label='Факт (Тестовая выборка)', color='green', linewidth=2)
plt.plot(recent_test['Date'], recent_test['ARIMA_Forecast'], label='Прогноз ARIMA', color='red', linestyle='--', linewidth=2)

# Настройка оформления
plt.title(f'Прогноз цены нефти Brent: модель ARIMA\nТочность на тесте: MAPE = {test_mape:.2f}%', fontsize=16, pad=20)
plt.xlabel('Дата', fontsize=12)
plt.ylabel('Цена (USD)', fontsize=12)
plt.legend(loc='best', fontsize=12)
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)

# Автоматическое размещение подписей дат
plt.gcf().autofmt_xdate()

plt.show()

"""ETS модель"""

print("ПОСТРОЕНИЕ ETS МОДЕЛЕЙ")

# Определяем сезонность - 7 дней
seasonal_periods = 7

# 1. Простая модель без сезонности
model_simple = ExponentialSmoothing(
    train_data['Close'],
    trend='add',
    seasonal=None,
    initialization_method='estimated'
).fit()

print("1. ПРОСТАЯ ETS МОДЕЛЬ (без сезонности):")
print(f"   AIC: {model_simple.aic:.2f}, BIC: {model_simple.bic:.2f}")

# 2. Модель с аддитивной сезонностью
try:
    model_add = ExponentialSmoothing(
        train_data['Close'],
        seasonal_periods=seasonal_periods,
        trend='add',
        seasonal='add',
        initialization_method='estimated'
    ).fit()
    add_model_success = True
    print("\n2. ETS МОДЕЛЬ С АДДИТИВНОЙ СЕЗОННОСТЬЮ:")
    print(f"   AIC: {model_add.aic:.2f}, BIC: {model_add.bic:.2f}")
except Exception as e:
    print(f"\n2. ОШИБКА при построении модели с аддитивной сезонностью: {e}")
    model_add = model_simple
    add_model_success = False

# 3. Модель с мультипликативной сезонностью
try:
    model_mul = ExponentialSmoothing(
        train_data['Close'],
        seasonal_periods=seasonal_periods,
        trend='add',
        seasonal='mul',
        initialization_method='estimated'
    ).fit()
    mul_model_success = True
    print("\n3. ETS МОДЕЛЬ С МУЛЬТИПЛИКАТИВНОЙ СЕЗОННОСТЬЮ:")
    print(f"   AIC: {model_mul.aic:.2f}, BIC: {model_mul.bic:.2f}")
except Exception as e:
    print(f"\n3. ОШИБКА при построении модели с мультипликативной сезонностью: {e}")
    model_mul = model_simple
    mul_model_success = False

# Прогнозирование на 2 дня
forecast_steps = len(test_data)
forecast_simple = model_simple.forecast(forecast_steps)
forecast_add = model_add.forecast(forecast_steps)
forecast_mul = model_mul.forecast(forecast_steps)

test_data['ETS_Simple_Forecast'] = forecast_simple.values
test_data['ETS_Add_Forecast'] = forecast_add.values
test_data['ETS_Mul_Forecast'] = forecast_mul.values

# Расчет метрик
def calculate_metrics(actual, forecast, model_name="Модель"):
    mae = mean_absolute_error(actual, forecast)
    rmse = np.sqrt(mean_squared_error(actual, forecast))
    mape = np.mean(np.abs((actual - forecast) / actual)) * 100
    r2 = 1 - (np.sum((actual - forecast) ** 2) / np.sum((actual - np.mean(actual)) ** 2))

    return {
        'model': model_name,
        'mae': mae,
        'rmse': rmse,
        'mape': mape,
        'r2': r2
    }

metrics_simple = calculate_metrics(test_data['Close'], forecast_simple, "ETS Simple")
metrics_add = calculate_metrics(test_data['Close'], forecast_add, "ETS Additive")
metrics_mul = calculate_metrics(test_data['Close'], forecast_mul, "ETS Multiplicative")

print("\nМЕТРИКИ КАЧЕСТВА НА ТЕСТОВОЙ ВЫБОРКЕ (2 дня):")
print("-"*60)
print(f"{'Модель':<20} {'MAE':>10} {'RMSE':>10} {'MAPE':>10} {'R²':>10}")
print("-"*60)
for metrics in [metrics_simple, metrics_add, metrics_mul]:
    print(f"{metrics['model']:<20} {metrics['mae']:>10.2f} {metrics['rmse']:>10.2f} "
          f"{metrics['mape']:>10.2f}% {metrics['r2']:>10.4f}")

# Визуализация лучшей модели
best_model_idx = np.argmin([m['rmse'] for m in [metrics_simple, metrics_add, metrics_mul]])
best_model_name = ['ETS Simple', 'ETS Additive', 'ETS Multiplicative'][best_model_idx]
best_forecast = [forecast_simple, forecast_add, forecast_mul][best_model_idx]

# Данные за последние 3 месяца
last_3_months = data['Date'].max() - timedelta(days=90)
recent_train = train_data[train_data['Date'] >= last_3_months]
recent_test = test_data

plt.figure(figsize=(14, 6))
plt.plot(recent_train['Date'], recent_train['Close'], label='Тренировочные данные',
         color='blue', linewidth=2, alpha=0.8)
plt.plot(recent_test['Date'], recent_test['Close'], label='Фактические значения',
         color='green', linewidth=2, marker='o')
plt.plot(recent_test['Date'], best_forecast, label=f'Прогноз {best_model_name}',
         color='red', linestyle='--', linewidth=3, marker='s')
plt.title(f'Лучшая ETS модель: {best_model_name}\n(последние 3 месяца)', fontsize=14, fontweight='bold')
plt.xlabel('Дата')
plt.ylabel('Цена Транснефти (руб.)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('ets_forecast_trnfp.png', dpi=300, bbox_inches='tight')
plt.show()

"""Проверка на ARCH эффекты. garch МОДЕЛЬ.




"""

print("ПРОВЕРКА НА ARCH ЭФФЕКТЫ. GARCH МОДЕЛЬ")

# Вычисляем доходности (логарифмические разности)
train_data['Returns'] = np.log(train_data['Close']).diff()
train_data['Returns_squared'] = train_data['Returns'] ** 2

# Тест на ARCH-эффекты
from statsmodels.stats.diagnostic import het_arch

returns_clean = train_data['Returns'].dropna()
arch_test = het_arch(returns_clean)
print("\nТест Engle на ARCH-эффекты:")
print(f"LM Statistic: {arch_test[0]:.4f}")
print(f"p-value: {arch_test[1]:.4f}")
print(f"F Statistic: {arch_test[2]:.4f}")
print(f"p-value (F-test): {arch_test[3]:.4f}")

if arch_test[1] < 0.05:
    print("\nВывод: Присутствуют ARCH-эффекты (гетероскедастичность). GARCH модель целесообразна.")

    # Построение GARCH(1,1) модели
    try:
        garch_model = arch_model(returns_clean * 100, vol='Garch', p=1, q=1, dist='normal')
        garch_fit = garch_model.fit(disp='off', show_warning=False)

        print("\nРезультаты GARCH(1,1) модели:")
        print(garch_fit.summary())
    except Exception as e:
        print(f"Ошибка при построении GARCH модели: {e}")
        test_data['GARCH_Volatility'] = np.nan
else:
    print("\nВывод: ARCH-эффекты статистически не значимы (p-value > 0.05). GARCH модель не требуется.")
    test_data['GARCH_Volatility'] = np.nan

"""тест Грейнджера. ADL модель"""

print("ТЕСТ ГРЕЙНДЖЕРА И ADL МОДЕЛЬ")

# Подготовка данных для теста Грейнджера
train_factors = train_data[['Close', 'USD_RUB', 'Brent']].copy()
train_factors = train_factors.dropna()

# Проверяем стационарность факторов
print("Проверка стационарности факторов для теста Грейнджера:")
for col in ['Close', 'USD_RUB', 'Brent']:
    result = adfuller(train_factors[col])
    p_val = result[1]
    print(f"{col}: p-value = {p_val:.4f}", end="")
    if p_val > 0.05:
        print(" (нестационарен)")
    else:
        print(" (стационарен)")

# Используем первые разности для нестационарных рядов
train_factors['Close_diff'] = train_factors['Close'].diff()
train_factors['USD_RUB_diff'] = train_factors['USD_RUB'].diff()
train_factors['Brent_diff'] = train_factors['Brent'].diff()
train_factors = train_factors.dropna()

# Тест Грейнджера причинности
print("\nТЕСТ ГРЕЙНДЖЕРА НА ПРИЧИННОСТЬ (лага = 5):")

# Проверяем, является ли USD/RUB причиной цен Транснефти
print("\n1. USD/RUB → Цены Транснефти:")
try:
    granger_test1 = grangercausalitytests(train_factors[['Close_diff', 'USD_RUB_diff']],
                                         maxlag=5, verbose=False)
    print(f"{'Лаг':<6} {'F-статистика':<15} {'p-value':<10} {'Вывод'}")
    print("-" * 55)
    for lag in range(1, 6):
        f_stat = granger_test1[lag][0]['ssr_ftest'][0]
        p_value = granger_test1[lag][0]['ssr_ftest'][1]
        conclusion = "✓ USD/RUB является причиной" if p_value < 0.05 else "✗ USD/RUB не является причиной"
        print(f"{lag:<6} {f_stat:<15.4f} {p_value:<10.4f} {conclusion}")
except Exception as e:
    print(f"  Ошибка: {e}")

# Проверяем, является ли цена на нефть Brent причиной цен Транснефти
print("\n2. Brent → Цены Транснефти:")
try:
    granger_test2 = grangercausalitytests(train_factors[['Close_diff', 'Brent_diff']],
                                         maxlag=5, verbose=False)
    print(f"{'Лаг':<6} {'F-статистика':<15} {'p-value':<10} {'Вывод'}")
    print("-" * 55)
    for lag in range(1, 6):
        f_stat = granger_test2[lag][0]['ssr_ftest'][0]
        p_value = granger_test2[lag][0]['ssr_ftest'][1]
        conclusion = "✓ Brent является причиной" if p_value < 0.05 else "✗ Brent не является причиной"
        print(f"{lag:<6} {f_stat:<15.4f} {p_value:<10.4f} {conclusion}")
except Exception as e:
    print(f"  Ошибка: {e}")

# Проверяем обратную причинность
print("\n3. Цены Транснефти → USD/RUB:")
try:
    granger_test3 = grangercausalitytests(train_factors[['USD_RUB_diff', 'Close_diff']],
                                         maxlag=5, verbose=False)
    print(f"{'Лаг':<6} {'F-статистика':<15} {'p-value':<10} {'Вывод'}")
    print("-" * 55)
    for lag in range(1, 6):
        f_stat = granger_test3[lag][0]['ssr_ftest'][0]
        p_value = granger_test3[lag][0]['ssr_ftest'][1]
        conclusion = "✓ Транснефть является причиной" if p_value < 0.05 else "✗ Транснефть не является причиной"
        print(f"{lag:<6} {f_stat:<15.4f} {p_value:<10.4f} {conclusion}")
except Exception as e:
    print(f"  Ошибка: {e}")

# Определяем лучший лаг на основе теста Грейнджера
print("ВЫБОР ФАКТОРОВ ДЛЯ ADL МОДЕЛИ:")

# Находим фактор с наименьшим p-value
best_factor = None
best_p_value = 1.0
best_lag = 1

factors_to_test = ['USD_RUB', 'Brent']
for factor in factors_to_test:
    try:
        test_result = grangercausalitytests(train_factors[['Close_diff', f'{factor}_diff']],
                                           maxlag=5, verbose=False)
        for lag in range(1, 6):
            p_val = test_result[lag][0]['ssr_ftest'][1]
            if p_val < best_p_value:
                best_p_value = p_val
                best_factor = factor
                best_lag = lag
    except:
        continue

if best_factor and best_p_value < 0.1:  # Используем 10% уровень значимости
    print(f"Выбран фактор: {best_factor} (лаг {best_lag}, p-value = {best_p_value:.4f})")

    # Построение ADL-модели с выбранным фактором
    print("ПОСТРОЕНИЕ ADL МОДЕЛИ")

    try:
        from statsmodels.api import OLS, add_constant

        # Создаем лаги для ADL модели
        lags_y = 3  # лаги зависимой переменной
        lags_x = best_lag  # лаги независимой переменной

        adl_data = pd.DataFrame()

        # Зависимая переменная (разности цен)
        adl_data['Y'] = train_factors['Close_diff']

        # Лаги зависимой переменной
        for i in range(1, lags_y + 1):
            adl_data[f'Y_lag{i}'] = train_factors['Close_diff'].shift(i)

        # Лаги независимой переменной
        for i in range(1, lags_x + 1):
            adl_data[f'X_lag{i}'] = train_factors[f'{best_factor}_diff'].shift(i)

        adl_data = adl_data.dropna()

        # Определение независимых переменных
        X_cols = [col for col in adl_data.columns if col != 'Y']
        X = add_constant(adl_data[X_cols])
        y = adl_data['Y']

        # Оценка ADL модели
        adl_model = OLS(y, X).fit()

        print("Результаты ADL модели (зависимая переменная: разность цен Транснефти):")
        print(adl_model.summary())

        # Прогноз на тестовую выборку
        print("\nПРОГНОЗ НА ТЕСТОВУЮ ВЫБОРКУ (2 дня):")

        # Подготовка тестовых данных
        test_factors = test_data[['Close', 'USD_RUB', 'Brent']].copy()
        test_factors['Close_diff'] = test_factors['Close'].diff()
        test_factors[f'{best_factor}_diff'] = test_factors[best_factor].diff()

        # Создаем прогноз шаг за шагом
        adl_predictions = []

        # Последние значения из тренировочной выборки
        last_y = train_factors['Close_diff'].iloc[-lags_y:].values
        last_x = train_factors[f'{best_factor}_diff'].iloc[-lags_x:].values

        for i in range(len(test_data)):
            # Подготовка данных для прогноза
            X_pred = [1]  # константа

            # Лаги зависимой переменной
            for lag in range(1, lags_y + 1):
                if i == 0:
                    X_pred.append(last_y[-lag])
                else:
                    if lag <= i:
                        X_pred.append(adl_predictions[i-lag])
                    else:
                        X_pred.append(last_y[-(lag-i)])

            # Лаги независимой переменной
            for lag in range(1, lags_x + 1):
                if i == 0:
                    X_pred.append(last_x[-lag])
                else:
                    if lag <= i:
                        if i-lag < len(test_factors):
                            X_pred.append(test_factors[f'{best_factor}_diff'].iloc[i-lag]
                                        if pd.notna(test_factors[f'{best_factor}_diff'].iloc[i-lag]) else 0)
                        else:
                            X_pred.append(0)
                    else:
                        X_pred.append(last_x[-(lag-i)])

            # Прогноз разности
            pred = np.dot(X_pred, adl_model.params)
            adl_predictions.append(pred)

        # Преобразуем прогнозы разностей обратно в цены
        last_price = train_data['Close'].iloc[-1]
        adl_price_forecast = [last_price]

        for diff in adl_predictions:
            adl_price_forecast.append(adl_price_forecast[-1] + diff)

        # Первое значение - это last_price, остальные - прогнозы
        test_data['ADL_Forecast'] = adl_price_forecast[1:]

        # Расчет метрик
        adl_mae = mean_absolute_error(test_data['Close'], test_data['ADL_Forecast'])
        adl_rmse = np.sqrt(mean_squared_error(test_data['Close'], test_data['ADL_Forecast']))
        adl_mape = mean_absolute_percentage_error(test_data['Close'], test_data['ADL_Forecast']) * 100

        print(f"\nМетрики ADL модели:")
        print(f"MAE: {adl_mae:.2f}")
        print(f"RMSE: {adl_rmse:.2f}")
        print(f"MAPE: {adl_mape:.2f}%")

        # Визуализация прогноза ADL (последние 3 месяца)
        last_3_months = data['Date'].max() - timedelta(days=90)
        recent_train = train_data[train_data['Date'] >= last_3_months]
        recent_test = test_data

        fig, axes = plt.subplots(2, 1, figsize=(14, 10))

        # 1. Прогноз цен
        axes[0].plot(recent_train['Date'], recent_train['Close'],
                    label='Тренировочные данные', color='blue', linewidth=2)
        axes[0].plot(recent_test['Date'], recent_test['Close'],
                    label='Фактические тестовые данные', color='red', linewidth=2, marker='o')
        axes[0].plot(recent_test['Date'], recent_test['ADL_Forecast'],
                    label='Прогноз ADL', color='brown', linestyle='--', linewidth=3, marker='s')
        axes[0].set_title(f'Прогноз ADL модели с фактором {best_factor} (последние 3 месяца)',
                         fontsize=14, fontweight='bold')
        axes[0].set_xlabel('Дата')
        axes[0].set_ylabel('Цена Транснефти (руб.)')
        axes[0].legend()
        axes[0].grid(True, alpha=0.3)

        # 2. График факторов
        axes[1].plot(train_data['Date'], train_data[best_factor],
                    label=f'{best_factor} (тренировка)', color='green', linewidth=1, alpha=0.7)
        axes[1].plot(test_data['Date'], test_data[best_factor],
                    label=f'{best_factor} (тест)', color='orange', linewidth=2, marker='o')
        axes[1].set_title(f'Динамика фактора {best_factor}', fontsize=12)
        axes[1].set_xlabel('Дата')
        axes[1].set_ylabel(f'{best_factor}')
        axes[1].legend()
        axes[1].grid(True, alpha=0.3)

        plt.tight_layout()
        plt.savefig('adl_forecast_trnfp.png', dpi=300, bbox_inches='tight')
        plt.show()
    except Exception as e:
        print(f"Ошибка при построении ADL модели: {e}")
        print(f"Трассировка ошибки: {traceback.format_exc()}")
        test_data['ADL_Forecast'] = np.nan
else:
    print("Нет статистически значимых факторов для построения ADL модели (p-value > 0.1)")
    test_data['ADL_Forecast'] = np.nan

"""prophet модель"""

print("PROPHET МОДЕЛЬ")

# Подготовка данных для Prophet
prophet_train = train_data[['Date', 'Close', 'USD_RUB', 'Brent']].copy()
prophet_train.columns = ['ds', 'y', 'USD_RUB', 'Brent']

# Создаем и обучаем модель Prophet
prophet_model = Prophet(
    yearly_seasonality=True,
    weekly_seasonality=True,
    daily_seasonality=False,
    seasonality_mode='additive'
)

# Добавляем дополнительные регрессоры
prophet_model.add_regressor('USD_RUB')
prophet_model.add_regressor('Brent')

prophet_model.fit(prophet_train)

# Создаем фрейм для прогноза
future = prophet_model.make_future_dataframe(periods=len(test_data))

# Добавляем значения регрессоров в будущий период
future['USD_RUB'] = data['USD_RUB'].values[:len(future)]
future['Brent'] = data['Brent'].values[:len(future)]

# Прогноз
forecast = prophet_model.predict(future)

# Извлекаем прогноз для тестового периода
test_forecast = forecast.iloc[-len(test_data):]
test_data['Prophet_Forecast'] = test_forecast['yhat'].values

# Расчет метрик Prophet
prophet_mse = mean_squared_error(test_data['Close'], test_data['Prophet_Forecast'])
prophet_rmse = np.sqrt(prophet_mse)
prophet_mae = mean_absolute_error(test_data['Close'], test_data['Prophet_Forecast'])
prophet_mape = mean_absolute_percentage_error(test_data['Close'], test_data['Prophet_Forecast']) * 100

print(f"\nМЕТРИКИ PROPHET МОДЕЛИ:")
print(f"MAE: {prophet_mae:.2f}")
print(f"RMSE: {prophet_rmse:.2f}")
print(f"MAPE: {prophet_mape:.2f}%")

# Визуализация последних 3 месяцев
last_3_months = data['Date'].max() - timedelta(days=90)
recent_train = train_data[train_data['Date'] >= last_3_months]
recent_test = test_data

fig, ax = plt.subplots(figsize=(14, 6))
ax.plot(recent_train['Date'], recent_train['Close'], label='Тренировочные данные',
        color='blue', linewidth=2)
ax.plot(recent_test['Date'], recent_test['Close'], label='Фактические значения',
        color='green', linewidth=2, marker='o')
ax.plot(recent_test['Date'], test_data['Prophet_Forecast'], label='Прогноз Prophet',
        color='purple', linestyle='--', linewidth=3, marker='s')
ax.fill_between(recent_test['Date'],
                 test_forecast['yhat_lower'].values,
                 test_forecast['yhat_upper'].values,
                 alpha=0.2, color='purple', label='Доверительный интервал')
ax.set_title('Прогноз Prophet модели (последние 3 месяца)', fontsize=14, fontweight='bold')
ax.set_xlabel('Дата')
ax.set_ylabel('Цена Транснефти (руб.)')
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('prophet_forecast_trnfp.png', dpi=300, bbox_inches='tight')
plt.show()

"""Сравнение моделей"""

# Собираем все прогнозы в один DataFrame
all_forecasts = test_data[['Date', 'Close']].copy()

# Список всех моделей и их прогнозов
models_forecasts = {
    'ARIMA': 'ARIMA_Forecast' if 'ARIMA_Forecast' in test_data.columns else None,
    'ETS_Simple': 'ETS_Simple_Forecast' if 'ETS_Simple_Forecast' in test_data.columns else None,
    'ETS_Add': 'ETS_Add_Forecast' if 'ETS_Add_Forecast' in test_data.columns else None,
    'ETS_Mul': 'ETS_Mul_Forecast' if 'ETS_Mul_Forecast' in test_data.columns else None,
    'ADL': 'ADL_Forecast' if 'ADL_Forecast' in test_data.columns else None,
    'Prophet': 'Prophet_Forecast' if 'Prophet_Forecast' in test_data.columns else None
}

# Добавляем прогнозы в общий DataFrame
for model_name, forecast_col in models_forecasts.items():
    if forecast_col and forecast_col in test_data.columns:
        all_forecasts[model_name] = test_data[forecast_col]

# Расчет метрик для всех моделей
results = []

for model_name in all_forecasts.columns:
    if model_name not in ['Date', 'Close']:
        actual = all_forecasts['Close']
        forecast = all_forecasts[model_name]

        # Проверяем, что прогнозы не NaN
        if forecast.isna().any():
            continue

        mae = mean_absolute_error(actual, forecast)
        rmse = np.sqrt(mean_squared_error(actual, forecast))
        mape = mean_absolute_percentage_error(actual, forecast) * 100

        # Рассчитываем R²
        ss_res = np.sum((actual - forecast) ** 2)
        ss_tot = np.sum((actual - np.mean(actual)) ** 2)
        r2 = 1 - (ss_res / ss_tot) if ss_tot != 0 else 0

        # Directional Accuracy (точность направления)
        direction_actual = np.sign(actual.diff().dropna())
        direction_forecast = np.sign(forecast.diff().dropna())

        # Проверяем, что массивы имеют одинаковую длину
        min_len = min(len(direction_actual), len(direction_forecast))
        if min_len > 0:
            direction_actual = direction_actual.iloc[:min_len]
            direction_forecast = direction_forecast.iloc[:min_len]
            directional_accuracy = np.mean(direction_actual == direction_forecast) * 100
        else:
            directional_accuracy = 0

        results.append({
            'Модель': model_name,
            'MAE': mae,
            'RMSE': rmse,
            'MAPE (%)': mape,
            'R²': r2,
            'Точность направления (%)': directional_accuracy
        })

# Создаем DataFrame с результатами
results_df = pd.DataFrame(results)

# Сортируем по RMSE (лучшая модель сверху)
results_df = results_df.sort_values('RMSE').reset_index(drop=True)

print("\nТАБЛИЦА СРАВНЕНИЯ МОДЕЛЕЙ:")
print("="*80)
print(results_df.to_string(index=False, float_format=lambda x: f"{x:.4f}" if abs(x) < 1000 else f"{x:.2f}"))
print("="*80)

# Определяем лучшую модель
best_model_name = results_df.iloc[0]['Модель']
best_model_metrics = results_df.iloc[0]

print(f"\n🏆 ЛУЧШАЯ МОДЕЛЬ: {best_model_name}")
print(f"   RMSE: {best_model_metrics['RMSE']:.2f}")
print(f"   MAPE: {best_model_metrics['MAPE (%)']:.2f}%")
print(f"   R²: {best_model_metrics['R²']:.4f}")

# Визуализация всех прогнозов
plt.figure(figsize=(15, 10))

# Построение фактических значений
plt.plot(test_data['Date'], test_data['Close'],
         label='Фактические значения',
         color='black', linewidth=3, marker='o', markersize=8)

# Цвета для разных моделей
colors = ['red', 'blue', 'green', 'orange', 'purple', 'brown']
color_idx = 0

# Построение прогнозов всех моделей
for idx, model_name in enumerate(all_forecasts.columns):
    if model_name not in ['Date', 'Close']:
        if model_name in all_forecasts.columns:
            plt.plot(all_forecasts['Date'], all_forecasts[model_name],
                    label=f'{model_name} (MAPE: {results_df[results_df["Модель"]==model_name]["MAPE (%)"].values[0]:.2f}%)',
                    color=colors[color_idx % len(colors)],
                    linestyle='--',
                    linewidth=2,
                    marker='s',
                    markersize=6)
            color_idx += 1

plt.title('Сравнение прогнозов всех моделей на тестовой выборке (2 дня)',
          fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Дата', fontsize=12)
plt.ylabel('Цена акции Транснефти (руб.)', fontsize=12)
plt.legend(loc='best', fontsize=10)
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)

# Добавляем аннотации с метриками лучшей модели
best_forecast = all_forecasts[best_model_name]
for i, (date, actual, forecast) in enumerate(zip(test_data['Date'], test_data['Close'], best_forecast)):
    error_pct = ((actual - forecast) / actual) * 100
    plt.annotate(f'{error_pct:+.1f}%',
                xy=(date, forecast),
                xytext=(0, 10),
                textcoords='offset points',
                ha='center',
                fontsize=9,
                color='red' if error_pct > 0 else 'green')

plt.tight_layout()
plt.savefig('all_models_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

"""Прогноз на два периода"""

# Определяем лучшую модель (ARIMA)
best_model_name = "ARIMA"
print(f" Выбрана лучшая модель: {best_model_name}")

#обученная модель из предыдущего кода

#Прогноз на 2 дня вперед
forecast_days = 2
arima_forecast = arima_fit.forecast(steps=forecast_days)

#Создаем даты для прогноза
last_date = data['Date'].iloc[-1]
forecast_dates = [last_date + timedelta(days=i+1) for i in range(forecast_days)]

#Создаем DataFrame с прогнозом
forecast_df = pd.DataFrame({
    'Дата': forecast_dates,
    'Прогноз_цена': arima_forecast.values,
    'Модель': best_model_name
})

#Рассчитываем изменения относительно последней известной цены
last_price = data['Close'].iloc[-1]
forecast_df['Изменение_абс'] = forecast_df['Прогноз_цена'] - last_price
forecast_df['Изменение_%'] = (forecast_df['Изменение_абс'] / last_price * 100).round(2)

print(f"\n ИСХОДНЫЕ ДАННЫЕ:")
print(f"Последняя известная цена ({last_date.strftime('%d.%m.%Y')}): {last_price:.2f} руб.")
print(f"Параметры ARIMA модели: {arima_fit.model_orders}")

print("\n ПРОГНОЗ НА 2 ДНЯ:")
print("-" * 70)
for i, row in forecast_df.iterrows():
    change_sign = "+" if row['Изменение_%'] > 0 else ""
    print(f"{row['Дата'].strftime('%d.%m.%Y')} ({row['Дата'].strftime('%A')}):")
    print(f"  Прогноз цены: {row['Прогноз_цена']:.2f} руб.")
    print(f"  Изменение: {change_sign}{row['Изменение_%']}% ({change_sign}{row['Изменение_абс']:.2f} руб.)")
    print()

# Визуализация прогноза
plt.figure(figsize=(12, 6))

# Исторические данные (последние 30 дней)
historical_days = 30
historical_data = data.tail(historical_days)

# Построение графика
plt.plot(historical_data['Date'], historical_data['Close'],
         label='Исторические данные', color='blue', linewidth=2, marker='o')

plt.plot(forecast_df['Дата'], forecast_df['Прогноз_цена'],
         label='Прогноз ARIMA', color='red',
         linestyle='--', marker='s', linewidth=3, markersize=8)

# Вертикальная линия разделения
plt.axvline(x=last_date, color='gray', linestyle=':', alpha=0.5, label='Текущая дата')

# Добавление значений на график
for i, row in forecast_df.iterrows():
    plt.annotate(f"{row['Прогноз_цена']:.2f}",
                xy=(row['Дата'], row['Прогноз_цена']),
                xytext=(0, 10),
                textcoords='offset points',
                ha='center',
                fontweight='bold',
                color='red')

plt.title(f'Прогноз цены акций Транснефти на 2 дня\nМодель: ARIMA{arima_fit.model_orders}',
          fontsize=14, fontweight='bold')
plt.xlabel('Дата')
plt.ylabel('Цена (руб.)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig('arima_2day_forecast.png', dpi=300, bbox_inches='tight')
plt.show()